### ISSUE TITLE
Useless requirements in requirements.txt

### ISSUE THREAD

**Issue by ghost** [buckydevv/World#2]
In the [requirements.txt](https://github.com/shuanaongithub/World/blob/main/requirements.txt), there is an abundance of missing/unused requirements.

Some of which include

- mysql-connector-python
- aggdraw
- spotipy
- psutil

**The fix**

Run `pip freeze > requirements.txt` or use Pipenv instead of relying on a .txt file

**Comment by buckydevv** [comment]
thx
